name: Build and push base docker image

on:
  push:
    branches: ["main"]
    paths:
      - "actions-runner/**"
  pull_request:
    branches: ["main"]
    paths:
      - "actions-runner/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: actions-runner
  ACTIONS_VERSION: 2.321.0

jobs:
  build-actions-runner:
    if: "!contains(github.event.head_commit.message, '[no-ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set repository owner
        id: set_repo_owner_lower
        shell: bash
        run: |
          echo "REPOSITORY_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}
          flavor: latest=auto
          tags: type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: actions-runner
          push: true
          build-args: VERSION=${{ env.ACTIONS_VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.ACTIONS_VERSION }}
